# Generated by Django 4.2.15 on 2026-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
