# Generated by Django 5.1.1 on 2026-07-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_year'),
        ('reviews', '0003_review_unique_review_per_title'),
    ]

    operations = [
    ]
